
trigger:

  - platform: homeassistant
    event: start

  - platform: time
    at: '22:55'

action:

  - service: input_datetime.set_datetime
    entity_id: input_datetime.confort_on_morning_working_day_time_computed
    data:
      time: '{{ states.input_datetime.confort_on_morning_working_day_time.state }}'

  - service: input_datetime.set_datetime
    entity_id: input_datetime.confort_on_non_working_day_time_computed
    data:
      time: '{{ states.input_datetime.confort_on_non_working_day_time.state }}'
