
logger:
  default: info
  
homeassistant:

  name: mama
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  time_zone: !secret time_zone
  external_url: !secret external_url
  internal_url: !secret internal_url
  packages: !include_dir_named packages

default_config:
        
lovelace:

  mode: storage

  dashboards:

    heating-dashboard:

      title: Chauffage
      filename: dashboards/heating.yaml
      mode: yaml
      icon: mdi:radiator
      show_in_sidebar: true

python_script:

frontend:

  extra_module_url:
    - /local/simple-thermostat.js?v=1
