
homeassistant:

  name: Mama
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  time_zone: !secret time_zone
  external_url: !secret external_url
  internal_url: !secret internal_url

  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
        
lovelace:

  mode: storage
  # add resource /local/simple-thermostat.js?v=1

  dashboards:

    heating-dashboard:

      title: Chauffage
      filename: dashboards/heating.yaml
      mode: yaml
      icon: mdi:radiator
      show_in_sidebar: true

logger:
  default: info

python_script:

meteo_france:
  - city: !secret wheater_city

automation: !include_dir_list includes/automation/
input_datetime: !include_dir_merge_named includes/input_datetime
input_boolean: !include_dir_merge_named includes/input_boolean

# TODO Tester ça pour les ressources JS
# frontend:
#   extra_module_url:
#     - /local/my_module.js
#   extra_js_url_es5:
#     - /local/my_es5.js
