alias: "Confort jours travaillés"
trigger:

  - platform: time
    at: input_datetime.confort_on_morning_working_day_time_computed

  - platform: time
    at: input_datetime.confort_on_afternoon_working_day_time

condition:

  condition: and
  conditions:

    - condition: state
      entity_id: binary_sensor.workday
      state: 'on'

action:

  - service: input_select.select_option
    data:
      entity_id:
        - input_select.thermostat_cuisine_mode
        - input_select.thermostat_sejour_mode
      option: 'confort'
      