alias: "Confort les jours à la maison"
trigger:

  platform: time
  at: input_datetime.confort_on_non_working_day_time_computed

condition:

  - condition: state
    entity_id: binary_sensor.presence
    state: 'on'

action:

  - service: input_select.select_option
    data:
      entity_id:
        - input_select.thermostat_salon_mode
        - input_select.thermostat_cuisine_mode
        - input_select.thermostat_sejour_mode
      option: 'confort'
