alias: "Les modes des thermostats"
trigger:

  - platform: state
    entity_id:
      - input_select.thermostat_salon_mode
      - input_select.thermostat_cuisine_mode
      - input_select.thermostat_sejour_mode
      - input_select.thermostat_chambre_colin_mode

action:

  - service: climate.set_temperature
    data:
      entity_id: >
        {{ 'climate.' + trigger.entity_id.split('.')[1].replace('_mode', '') }}
      temperature: >
        {{ states('input_number.' + trigger.entity_id.split('.')[1] + '_' + states(trigger.entity_id)) | float }}

mode: parallel
