alias: Allumer radiateur SdB le matin
trigger:

  - platform: time
    at: input_datetime.bathroom_heater_time

action:

  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.fake_smart_plug
