
- platform: workday
  name: workday_base
  country: FRA
  workdays: [mon, tue, thu, fri]
  excludes: [wed, sat, sun, holiday]

- platform: template
  sensors:

    workday:
      friendly_name: "Jour travaillé"
      value_template: >-
        {{ is_state('binary_sensor.workday_base', 'on')
            and not (as_timestamp(now()) >= as_timestamp(strptime(states.input_datetime.custom_holiday_begin.state, '%Y-%m-%d'))  
              and as_timestamp(now()) <= as_timestamp(strptime(states.input_datetime.custom_holiday_end.state + ' 23:59:59', '%Y-%m-%d %H:%M:%S'))) }}
              