
input_datetime:

  compute_smart_starts_time:
    name: Heure de calcul de l'avance du chauffage
    has_date: false
    has_time: true
    initial: '01:00'

automation:

  alias: "Calculer l'avancement sur chauffage"
  trigger:

    - platform: time
      at: input_datetime.compute_smart_starts_time

  action:

    - service: python_script.smart_start_compute
      data:
        time_entity_id: input_datetime.confort_on_non_working_day_time
        computed_time_entity_id: input_datetime.confort_on_non_working_day_time_computed
        external_temperature_entity_id: sensor.home_external_temperature

    - service: python_script.smart_start_compute
      data:
        time_entity_id: input_datetime.confort_on_morning_working_day_time
        computed_time_entity_id: input_datetime.confort_on_morning_working_day_time_computed
        external_temperature_entity_id: sensor.home_external_temperature
